services:

  api_nlp:
    build:
      context: ../..
      dockerfile: ./docker/api_nlp/Dockerfile
    container_name: api_nlp
    volumes:
      - staticfiles_stanza:/app/api_nlp/staticfiles/stanza
      - staticfiles_marianmt:/app/api_nlp/staticfiles/marianmt
    networks:
      - local_network_api_nlp
      - shared_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -H 'X-Request-Id: healthcheck' --fail -f http://$$API_NLP_HOST:$$API_NLP_PORT/$$DOCS_URL" ]
      interval: 10s
      timeout: 30s
      retries: 3
    environment:
      - TZ=UTC

networks:
  local_network_api_nlp:
    driver: bridge
  shared_network:
    external: true

volumes:
  staticfiles_stanza: { }
