services:

  api_nlp:
    build:
      args:
        - BUILD_ENV=local
    command: /start_api_local.sh
    env_file:
      - ../../.envs/.docker-compose-local/.api_nlp
    expose:
      - "8001"
    ports:
      - "8001:8001"
