from core.enums import LevelSystemNamesEnum, LevelOrderEnum, LevelCEFRCodesEnum, TasksNamesEnum, \
    QueueTaskPrioritiesEnum, LanguagesISO2NamesEnum

TIMEZONES_DICT = {
    "UTC+14": "Etc/GMT-14",
    "UTC+13": "Etc/GMT-13",
    "UTC+12": "Etc/GMT-12",
    "UTC+11": "Etc/GMT-11",
    "UTC+10": "Etc/GMT-10",
    "UTC+9": "Etc/GMT-9",
    "UTC+8": "Etc/GMT-8",
    "UTC+7": "Etc/GMT-7",
    "UTC+6": "Etc/GMT-6",
    "UTC+5": "Etc/GMT-5",
    "UTC+4": "Etc/GMT-4",
    "UTC+3": "Etc/GMT-3",
    "UTC+2": "Etc/GMT-2",
    "UTC+1": "Etc/GMT-1",
    "UTC+0": "Etc/GMT+0",
    "UTC−1": "Etc/GMT+1",
    "UTC−2": "Etc/GMT+2",
    "UTC−3": "Etc/GMT+3",
    "UTC−4": "Etc/GMT+4",
    "UTC−5": "Etc/GMT+5",
    "UTC−6": "Etc/GMT+6",
    "UTC−7": "Etc/GMT+7",
    "UTC−8": "Etc/GMT+8",
    "UTC−9": "Etc/GMT+9",
    "UTC−10": "Etc/GMT+10",
    "UTC−11": "Etc/GMT+11",
    "UTC−12": "Etc/GMT+12",
}

COUNTRIES_DICT = {
    'AW': ('ABW', 'Aruba', 'Aruba'),
    'AF': ('AFG', 'Afghanistan', 'افغانستان'),
    'AO': ('AGO', 'Angola', 'Angola'),
    'AI': ('AIA', 'Anguilla', 'Anguilla'),
    'AX': ('ALA', 'Åland Islands', 'Åland'),
    'AL': ('ALB', 'Albania', 'Shqipëri'),
    'AD': ('AND', 'Andorra', 'Andorra'),
    'AE': ('ARE', 'United Arab Emirates', 'الإمارات العربية المتحدة'),
    'AR': ('ARG', 'Argentina', 'Argentina'),
    'AM': ('ARM', 'Armenia', 'Հայաստան'),
    'AS': ('ASM', 'American Samoa', 'Amerika Sāmoa'),
    'AQ': ('ATA', 'Antarctica', 'Antarctica'),
    'TF': ('ATF', 'French Southern Territories', 'Terres australes françaises'),
    'AG': ('ATG', 'Antigua and Barbuda', 'Antigua and Barbuda'),
    'AU': ('AUS', 'Australia', 'Australia'),
    'AT': ('AUT', 'Austria', 'Österreich'),
    'AZ': ('AZE', 'Azerbaijan', 'Azərbaycan'),
    'BI': ('BDI', 'Burundi', 'Burundi'),
    'BE': ('BEL', 'Belgium', 'België / Belgique / Belgien'),
    'BJ': ('BEN', 'Benin', 'Bénin'),
    'BQ': ('BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius en Saba'),
    'BF': ('BFA', 'Burkina Faso', 'Burkina Faso'),
    'BD': ('BGD', 'Bangladesh', 'বাংলাদেশ'),
    'BG': ('BGR', 'Bulgaria', 'България'),
    'BH': ('BHR', 'Bahrain', '‏البحرين'),
    'BS': ('BHS', 'Bahamas', 'Bahamas'),
    'BA': ('BIH', 'Bosnia and Herzegovina', 'Bosna i Hercegovina'),
    'BL': ('BLM', 'Saint Barthélemy', 'Saint-Barthélemy'),
    'BY': ('BLR', 'Belarus', 'Беларусь'),
    'BZ': ('BLZ', 'Belize', 'Belize'),
    'BM': ('BMU', 'Bermuda', 'Bermuda'),
    'BO': ('BOL', 'Bolivia (Plurinational State of)', 'Bolivia'),
    'BR': ('BRA', 'Brazil', 'Brasil'),
    'BB': ('BRB', 'Barbados', 'Barbados'),
    'BN': ('BRN', 'Brunei Darussalam', 'Brunei'),
    'BT': ('BTN', 'Bhutan', 'འབྲུག'),
    'BV': ('BVT', 'Bouvet Island', 'Bouvetøya'),
    'BW': ('BWA', 'Botswana', 'Botswana'),
    'CF': ('CAF', 'Central African Republic', 'République centrafricaine'),
    'CA': ('CAN', 'Canada', 'Canada'),
    'CC': ('CCK', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
    'CH': ('CHE', 'Switzerland', 'Schweiz / Suisse / Svizzera'),
    'CL': ('CHL', 'Chile', 'Chile'),
    'CN': ('CHN', 'China', '中国'),
    'CI': ('CIV', "Côte d'Ivoire", "Côte d'Ivoire"),
    'CM': ('CMR', 'Cameroon', 'Cameroun'),
    'CD': ('COD', 'Congo, Democratic Republic of the', 'République démocratique du Congo'),
    'CG': ('COG', 'Congo', 'République du Congo'),
    'CK': ('COK', 'Cook Islands', 'Cook Islands'),
    'CO': ('COL', 'Colombia', 'Colombia'),
    'KM': ('COM', 'Comoros', 'Komori'),
    'CV': ('CPV', 'Cabo Verde', 'Cabo Verde'),
    'CR': ('CRI', 'Costa Rica', 'Costa Rica'),
    'CU': ('CUB', 'Cuba', 'Cuba'),
    'CW': ('CUW', 'Curaçao', 'Curaçao'),
    'CX': ('CXR', 'Christmas Island', 'Christmas Island'),
    'KY': ('CYM', 'Cayman Islands', 'Cayman Islands'),
    'CY': ('CYP', 'Cyprus', 'Κύπρος'),
    'CZ': ('CZE', 'Czechia (Czech Republic)', 'Česká republika'),
    'DE': ('DEU', 'Germany', 'Deutschland'),
    'DJ': ('DJI', 'Djibouti', 'Djibouti'),
    'DM': ('DMA', 'Dominica', 'Dominica'),
    'DK': ('DNK', 'Denmark', 'Danmark'),
    'DO': ('DOM', 'Dominican Republic', 'República Dominicana'),
    'DZ': ('DZA', 'Algeria', 'الجزائر'),
    'EC': ('ECU', 'Ecuador', 'Ecuador'),
    'EG': ('EGY', 'Egypt', 'مصر'),
    'ER': ('ERI', 'Eritrea', 'ኤርትራ'),
    'EH': ('ESH', 'Western Sahara', 'الصحراء الغربية'),
    'ES': ('ESP', 'Spain', 'España'),
    'EE': ('EST', 'Estonia', 'Eesti'),
    'ET': ('ETH', 'Ethiopia', 'ኢትዮጵያ'),
    'FI': ('FIN', 'Finland', 'Suomi'),
    'FJ': ('FJI', 'Fiji', 'Fiji'),
    'FK': ('FLK', 'Falkland Islands (Malvinas)', 'Falkland Islands'),
    'FR': ('FRA', 'France', 'France'),
    'FO': ('FRO', 'Faroe Islands', 'Føroyar'),
    'FM': ('FSM', 'Micronesia (Federated States of)', 'Micronesia'),
    'GA': ('GAB', 'Gabon', 'Gabon'),
    'GB': ('GBR', 'United Kingdom of Great Britain and Northern Ireland', 'United Kingdom'),
    'GE': ('GEO', 'Georgia', 'საქართველო'),
    'GG': ('GGY', 'Guernsey', 'Guernsey'),
    'GH': ('GHA', 'Ghana', 'Ghana'),
    'GI': ('GIB', 'Gibraltar', 'Gibraltar'),
    'GN': ('GIN', 'Guinea', 'Guinée'),
    'GP': ('GLP', 'Guadeloupe', 'Guadeloupe'),
    'GM': ('GMB', 'Gambia', 'Gambia'),
    'GW': ('GNB', 'Guinea-Bissau', 'Guiné-Bissau'),
    'GQ': ('GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial'),
    'GR': ('GRC', 'Greece', 'Ελλάδα'),
    'GD': ('GRD', 'Grenada', 'Grenada'),
    'GL': ('GRL', 'Greenland', 'Kalaallit Nunaat'),
    'GT': ('GTM', 'Guatemala', 'Guatemala'),
    'GF': ('GUF', 'French Guiana', 'Guyane française'),
    'GU': ('GUM', 'Guam', 'Guam'),
    'GY': ('GUY', 'Guyana', 'Guyana'),
    'HK': ('HKG', 'Hong Kong', '香港'),
    'HM': ('HMD', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'),
    'HN': ('HND', 'Honduras', 'Honduras'),
    'HR': ('HRV', 'Croatia', 'Hrvatska'),
    'HT': ('HTI', 'Haiti', 'Haïti'),
    'HU': ('HUN', 'Hungary', 'Magyarország'),
    'ID': ('IDN', 'Indonesia', 'Indonesia'),
    'IM': ('IMN', 'Isle of Man', 'Isle of Man'),
    'IN': ('IND', 'India', 'भारत'),
    'IO': ('IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory'),
    'IE': ('IRL', 'Ireland', 'Éire'),
    'IR': ('IRN', 'Iran (Islamic Republic of)', 'ایران'),
    'IQ': ('IRQ', 'Iraq', 'العراق'),
    'IS': ('ISL', 'Iceland', 'Ísland'),
    'IL': ('ISR', 'Israel', 'ישראל'),
    'IT': ('ITA', 'Italy', 'Italia'),
    'JM': ('JAM', 'Jamaica', 'Jamaica'),
    'JE': ('JEY', 'Jersey', 'Jersey'),
    'JO': ('JOR', 'Jordan', 'الأردن'),
    'JP': ('JPN', 'Japan', '日本'),
    'KZ': ('KAZ', 'Kazakhstan', 'Қазақстан'),
    'KE': ('KEN', 'Kenya', 'Kenya'),
    'KG': ('KGZ', 'Kyrgyzstan', 'Кыргызстан'),
    'KH': ('KHM', 'Cambodia', 'កម្ពុជា'),
    'KI': ('KIR', 'Kiribati', 'Kiribati'),
    'KN': ('KNA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
    'KR': ('KOR', 'Korea, Republic of', '대한민국'),
    'KW': ('KWT', 'Kuwait', 'الكويت'),
    'LA': ('LAO', "Lao People's Democratic Republic", 'ລາວ'),
    'LB': ('LBN', 'Lebanon', 'لبنان'),
    'LR': ('LBR', 'Liberia', 'Liberia'),
    'LY': ('LBY', 'Libya', 'ليبيا'),
    'LC': ('LCA', 'Saint Lucia', 'Saint Lucia'),
    'LI': ('LIE', 'Liechtenstein', 'Liechtenstein'),
    'LK': ('LKA', 'Sri Lanka', 'ශ්‍රී ලංකාව / இலங்கை'),
    'LS': ('LSO', 'Lesotho', 'Lesotho'),
    'LT': ('LTU', 'Lithuania', 'Lietuva'),
    'LU': ('LUX', 'Luxembourg', 'Luxembourg'),
    'LV': ('LVA', 'Latvia', 'Latvija'),
    'MO': ('MAC', 'Macao', '澳門'),
    'MF': ('MAF', 'Saint Martin (French part)', 'Saint-Martin'),
    'MA': ('MAR', 'Morocco', 'المغرب'),
    'MC': ('MCO', 'Monaco', 'Monaco'),
    'MD': ('MDA', 'Moldova, Republic of', 'Moldova'),
    'MG': ('MDG', 'Madagascar', 'Madagasikara'),
    'MV': ('MDV', 'Maldives', 'ދިވެހި'),
    'MX': ('MEX', 'Mexico', 'México'),
    'MH': ('MHL', 'Marshall Islands', 'Marshall Islands'),
    'MK': ('MKD', 'North Macedonia', 'Северна Македонија'),
    'ML': ('MLI', 'Mali', 'Mali'),
    'MT': ('MLT', 'Malta', 'Malta'),
    'MM': ('MMR', 'Myanmar', 'မြန်မာ'),
    'ME': ('MNE', 'Montenegro', 'Crna Gora'),
    'MN': ('MNG', 'Mongolia', 'Монгол'),
    'MP': ('MNP', 'Northern Mariana Islands', 'Northern Mariana Islands'),
    'MZ': ('MOZ', 'Mozambique', 'Moçambique'),
    'MR': ('MRT', 'Mauritania', 'موريتانيا'),
    'MS': ('MSR', 'Montserrat', 'Montserrat'),
    'MQ': ('MTQ', 'Martinique', 'Martinique'),
    'MU': ('MUS', 'Mauritius', 'Mauritius'),
    'MW': ('MWI', 'Malawi', 'Malawi'),
    'MY': ('MYS', 'Malaysia', 'Malaysia'),
    'YT': ('MYT', 'Mayotte', 'Mayotte'),
    'NA': ('NAM', 'Namibia', 'Namibia'),
    'NC': ('NCL', 'New Caledonia', 'Nouvelle-Calédonie'),
    'NE': ('NER', 'Niger', 'Niger'),
    'NF': ('NFK', 'Norfolk Island', 'Norfolk Island'),
    'NG': ('NGA', 'Nigeria', 'Nigeria'),
    'NI': ('NIC', 'Nicaragua', 'Nicaragua'),
    'NU': ('NIU', 'Niue', 'Niue'),
    'NL': ('NLD', 'Netherlands', 'Nederland'),
    'NO': ('NOR', 'Norway', 'Norge / Noreg'),
    'NP': ('NPL', 'Nepal', 'नेपाल'),
    'NR': ('NRU', 'Nauru', 'Nauru'),
    'NZ': ('NZL', 'New Zealand', 'New Zealand'),
    'OM': ('OMN', 'Oman', 'عمان'),
    'PK': ('PAK', 'Pakistan', 'پاکستان'),
    'PA': ('PAN', 'Panama', 'Panamá'),
    'PN': ('PCN', 'Pitcairn', 'Pitcairn Islands'),
    'PE': ('PER', 'Peru', 'Perú'),
    'PH': ('PHL', 'Philippines', 'Pilipinas'),
    'PW': ('PLW', 'Palau', 'Palau'),
    'PG': ('PNG', 'Papua New Guinea', 'Papua Niugini'),
    'PL': ('POL', 'Poland', 'Polska'),
    'PR': ('PRI', 'Puerto Rico', 'Puerto Rico'),
    'KP': ('PRK', "Korea (Democratic People's Republic of)", '조선민주주의인민공화국'),
    'PT': ('PRT', 'Portugal', 'Portugal'),
    'PY': ('PRY', 'Paraguay', 'Paraguay'),
    'PS': ('PSE', 'Palestine, State of', 'فلسطين'),
    'PF': ('PYF', 'French Polynesia', 'Polynésie française'),
    'QA': ('QAT', 'Qatar', 'قطر'),
    'RE': ('REU', 'Réunion', 'La Réunion'),
    'RO': ('ROU', 'Romania', 'România'),
    'RU': ('RUS', 'Russian Federation', 'Россия'),
    'RW': ('RWA', 'Rwanda', 'Rwanda'),
    'SA': ('SAU', 'Saudi Arabia', 'المملكة العربية السعودية'),
    'SD': ('SDN', 'Sudan', 'السودان'),
    'SN': ('SEN', 'Senegal', 'Sénégal'),
    'SG': ('SGP', 'Singapore', 'Singapore'),
    'GS': ('SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia'),
    'SH': ('SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena'),
    'SJ': ('SJM', 'Svalbard and Jan Mayen', 'Svalbard og Jan Mayen'),
    'SB': ('SLB', 'Solomon Islands', 'Solomon Islands'),
    'SL': ('SLE', 'Sierra Leone', 'Sierra Leone'),
    'SV': ('SLV', 'El Salvador', 'El Salvador'),
    'SM': ('SMR', 'San Marino', 'San Marino'),
    'SO': ('SOM', 'Somalia', 'Soomaaliya'),
    'PM': ('SPM', 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon'),
    'RS': ('SRB', 'Serbia', 'Србија'),
    'SS': ('SSD', 'South Sudan', 'South Sudan'),
    'ST': ('STP', 'Sao Tome and Principe', 'São Tomé e Príncipe'),
    'SR': ('SUR', 'Suriname', 'Suriname'),
    'SK': ('SVK', 'Slovakia', 'Slovensko'),
    'SI': ('SVN', 'Slovenia', 'Slovenija'),
    'SE': ('SWE', 'Sweden', 'Sverige'),
    'SZ': ('SWZ', 'Eswatini', 'Eswatini'),
    'SX': ('SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten'),
    'SC': ('SYC', 'Seychelles', 'Seychelles'),
    'SY': ('SYR', 'Syrian Arab Republic', 'سوريا'),
    'TC': ('TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands'),
    'TD': ('TCD', 'Chad', 'Tchad'),
    'TG': ('TGO', 'Togo', 'Togo'),
    'TH': ('THA', 'Thailand', 'ประเทศไทย'),
    'TJ': ('TJK', 'Tajikistan', 'Тоҷикистон'),
    'TK': ('TKL', 'Tokelau', 'Tokelau'),
    'TM': ('TKM', 'Turkmenistan', 'Türkmenistan'),
    'TL': ('TLS', 'Timor-Leste', 'Timor-Leste'),
    'TO': ('TON', 'Tonga', 'Tonga'),
    'TT': ('TTO', 'Trinidad and Tobago', 'Trinidad and Tobago'),
    'TN': ('TUN', 'Tunisia', 'تونس'),
    'TR': ('TUR', 'Turkey', 'Türkiye'),
    'TV': ('TUV', 'Tuvalu', 'Tuvalu'),
    'TW': ('TWN', 'Taiwan, Province of China', '台灣'),
    'TZ': ('TZA', 'Tanzania, United Republic of', 'Tanzania'),
    'UG': ('UGA', 'Uganda', 'Uganda'),
    'UA': ('UKR', 'Ukraine', 'Україна'),
    'UY': ('URY', 'Uruguay', 'Uruguay'),
    'US': ('USA', 'United States of America', 'United States'),
    'UM': ('UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands'),
    'UZ': ('UZB', 'Uzbekistan', 'Ўзбекистон'),
    'VA': ('VAT', 'Holy See', 'Sancta Sedes'),
    'VC': ('VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'),
    'VE': ('VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuela'),
    'VG': ('VGB', 'Virgin Islands (British)', 'British Virgin Islands'),
    'VI': ('VIR', 'Virgin Islands (U.S.)', 'Virgin Islands of the United States'),
    'VN': ('VNM', 'Vietnam', 'Việt Nam'),
    'VU': ('VUT', 'Vanuatu', 'Vanuatu'),
    'WF': ('WLF', 'Wallis and Futuna', 'Wallis et Futuna'),
    'WS': ('WSM', 'Samoa', 'Samoa'),
    'YE': ('YEM', 'Yemen', 'اليمن'),
    'ZA': ('ZAF', 'South Africa', 'South Africa'),
    'ZM': ('ZMB', 'Zambia', 'Zambia'),
    'ZW': ('ZWE', 'Zimbabwe', 'Zimbabwe'),
}

LANGUAGES_DICT = {
    'AB': ('ABK', 'Abkhazian', 'Аҧсшәа'),
    'AA': ('AAR', 'Afar', 'Afaraf'),
    'AF': ('AFR', 'Afrikaans', 'Afrikaans'),
    'AK': ('AKA', 'Akan', 'Akan'),
    'SQ': ('SQI', 'Albanian', 'Shqip'),
    'AM': ('AMH', 'Amharic', 'አማርኛ'),
    'AR': ('ARA', 'Arabic', 'العربية'),
    'AN': ('ARG', 'Aragonese', 'Aragonés'),
    'HY': ('HYE', 'Armenian', 'Հայերեն'),
    'AS': ('ASM', 'Assamese', 'অসমীয়া'),
    'AV': ('AVA', 'Avaric', 'Авар МацӀ'),
    'AE': ('AVE', 'Avestan', 'Avesta'),
    'AY': ('AYM', 'Aymara', 'Aymar Aru'),
    'AZ': ('AZE', 'Azerbaijani', 'Azərbaycan Dili'),
    'BM': ('BAM', 'Bambara', 'Bamanankan'),
    'BA': ('BAK', 'Bashkir', 'Башҡорт Теле'),
    'EU': ('EUS', 'Basque', 'Euskara'),
    'BE': ('BEL', 'Belarusian', 'Беларуская'),
    'BN': ('BEN', 'Bengali', 'বাংলা'),
    'BI': ('BIS', 'Bislama', 'Bislama'),
    'BS': ('BOS', 'Bosnian', 'Bosanski Jezik'),
    'BR': ('BRE', 'Breton', 'Brezhoneg'),
    'BG': ('BUL', 'Bulgarian', 'Български Език'),
    'MY': ('MYA', 'Burmese', 'ဗမာစာ'),
    'CA': ('CAT', 'Catalan, Valencian', 'Català, Valencià'),
    'CH': ('CHA', 'Chamorro', 'Chamoru'),
    'CE': ('CHE', 'Chechen', 'Нохчийн Мотт'),
    'NY': ('NYA', 'Chichewa, Chewa, Nyanja', 'ChiCheŵa, Chinyanja'),
    'ZH': ('ZHO', 'Chinese', '中文 (Zhōngwén), 汉语, 漢語'),
    'CU': ('CHU', 'Church Slavonic, Old Slavonic, Old Church Slavonic', 'ѩзыкъ Словѣньскъ'),
    'CV': ('CHV', 'Chuvash', 'Чӑваш Чӗлхи'),
    'KW': ('COR', 'Cornish', 'Kernewek'),
    'CO': ('COS', 'Corsican', 'Corsu'),
    'CR': ('CRE', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ'),
    'HR': ('HRV', 'Croatian', 'Hrvatski'),
    'CS': ('CES', 'Czech', 'Česky, Čeština'),
    'DA': ('DAN', 'Danish', 'Dansk'),
    'DV': ('DIV', 'Divehi, Dhivehi, Maldivian', 'ދިވެހި'),
    'NL': ('NLD', 'Dutch, Flemish', 'Nederlands, Vlaams'),
    'DZ': ('DZO', 'Dzongkha', 'རྫོང་ཁ'),
    'EN': ('ENG', 'English', 'English'),
    'EO': ('EPO', 'Esperanto', 'Esperanto'),
    'ET': ('EST', 'Estonian', 'Eesti, Eesti Keel'),
    'EE': ('EWE', 'Ewe', 'Eʋegbe'),
    'FO': ('FAO', 'Faroese', 'Føroyskt'),
    'FJ': ('FIJ', 'Fijian', 'Vosa Vakaviti'),
    'FI': ('FIN', 'Finnish', 'Suomi, Suomen Kieli'),
    'FR': ('FRA', 'French', 'Français'),
    'FY': ('FRY', 'Western Frisian', 'Frysk'),
    'FF': ('FUL', 'Fulah', 'Fulfulde'),
    'GD': ('GLA', 'Gaelic, Scottish Gaelic', 'Gàidhlig'),
    'GL': ('GLG', 'Galician', 'Galego'),
    'LG': ('LUG', 'Ganda', 'Luganda'),
    'KA': ('KAT', 'Georgian', 'ქართული'),
    'DE': ('DEU', 'German', 'Deutsch'),
    'EL': ('ELL', 'Greek, Modern (1453–)', 'Ελληνικά'),
    'KL': ('KAL', 'Kalaallisut, Greenlandic', 'Kalaallisut, Kalaallit Oqaasii'),
    'GN': ('GRN', 'Guarani', 'Avañeẽ'),
    'GU': ('GUJ', 'Gujarati', 'ગુજરાતી'),
    'HT': ('HAT', 'Haitian, Haitian Creole', 'Kreyòl Ayisyen'),
    'HA': ('HAU', 'Hausa', 'Hausa, هَوُسَ'),
    'HE': ('HEB', 'Hebrew', 'עברית'),
    'HZ': ('HER', 'Herero', 'Otjiherero'),
    'HI': ('HIN', 'Hindi', 'हिन्दी, हिंदी'),
    'HO': ('HMO', 'Hiri Motu', 'Hiri Motu'),
    'HU': ('HUN', 'Hungarian', 'Magyar'),
    'IS': ('ISL', 'Icelandic', 'Íslenska'),
    'IO': ('IDO', 'Ido', 'Ido'),
    'IG': ('IBO', 'Igbo', 'Asụsụ Igbo'),
    'ID': ('IND', 'Indonesian', 'Bahasa Indonesia'),
    'IA': ('INA', 'Interlingua (International Auxiliary Language Association)', 'Interlingua'),
    'IE': ('ILE', 'Interlingue, Occidental', 'Interlingue'),
    'IU': ('IKU', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
    'IK': ('IPK', 'Inupiaq', 'Iñupiaq, Iñupiatun'),
    'GA': ('GLE', 'Irish', 'Gaeilge'),
    'IT': ('ITA', 'Italian', 'Italiano'),
    'JA': ('JPN', 'Japanese', '日本語 (にほんご)'),
    'JV': ('JAV', 'Javanese', 'ꦧꦱꦗꦮ, Basa Jawa'),
    'KN': ('KAN', 'Kannada', 'ಕನ್ನಡ'),
    'KR': ('KAU', 'Kanuri', 'Kanuri'),
    'KS': ('KAS', 'Kashmiri', 'कश्मीरी, كشميري‎'),
    'KK': ('KAZ', 'Kazakh', 'Қазақ Тілі'),
    'KM': ('KHM', 'Central Khmer', 'ភាសាខ្មែរ'),
    'KI': ('KIK', 'Kikuyu, Gikuyu', 'Gĩkũyũ'),
    'RW': ('KIN', 'Kinyarwanda', 'Ikinyarwanda'),
    'KY': ('KIR', 'Kirghiz, Kyrgyz', 'Кыргыз Тили'),
    'KV': ('KOM', 'Komi', 'Коми Кыв'),
    'KG': ('KON', 'Kongo', 'KiKongo'),
    'KO': ('KOR', 'Korean', '한국어'),
    'KJ': ('KUA', 'Kuanyama, Kwanyama', 'Kuanyama'),
    'KU': ('KUR', 'Kurdish', 'Kurdî, كوردی‎'),
    'LO': ('LAO', 'Lao', 'ພາສາລາວ'),
    'LA': ('LAT', 'Latin', 'Latine, Lingua Latina'),
    'LV': ('LAV', 'Latvian', 'Latviešu Valoda'),
    'LI': ('LIM', 'Limburgan, Limburger, Limburgish', 'Limburgs'),
    'LN': ('LIN', 'Lingala', 'Lingála'),
    'LT': ('LIT', 'Lithuanian', 'Lietuvių Kalba'),
    'LU': ('LUB', 'Luba-Katanga', 'Tshiluba'),
    'LB': ('LTZ', 'Luxembourgish, Letzeburgesch', 'Lëtzebuergesch'),
    'MK': ('MKD', 'Macedonian', 'Македонски Јазик'),
    'MG': ('MLG', 'Malagasy', 'Malagasy Fiteny'),
    'MS': ('MSA', 'Malay', 'Bahasa Melayu, بهاس ملايو‎'),
    'ML': ('MAL', 'Malayalam', 'മലയാളം'),
    'MT': ('MLT', 'Maltese', 'Malti'),
    'GV': ('GLV', 'Manx', 'Gaelg, Gailck'),
    'MI': ('MRI', 'Maori', 'Te Reo Māori'),
    'MR': ('MAR', 'Marathi', 'मराठी'),
    'MH': ('MAH', 'Marshallese', 'Kajin M̧ajeļ'),
    'MN': ('MON', 'Mongolian', 'Монгол'),
    'NA': ('NAU', 'Nauru', 'Ekakairũ Naoero'),
    'NV': ('NAV', 'Navajo, Navaho', 'Diné Bizaad, Dinékʼehǰí'),
    'ND': ('NDE', 'North Ndebele', 'IsiNdebele'),
    'NR': ('NBL', 'South Ndebele', 'IsiNdebele'),
    'NG': ('NDO', 'Ndonga', 'Owambo'),
    'NE': ('NEP', 'Nepali', 'नेपाली'),
    'NO': ('NOR', 'Norwegian', 'Norsk'),
    'NB': ('NOB', 'Norwegian Bokmål', 'Norsk Bokmål'),
    'NN': ('NNO', 'Norwegian Nynorsk', 'Norsk Nynorsk'),
    'II': ('III', 'Sichuan Yi, Nuosu', 'ꆈꌠ꒿ Nuosuhxop'),
    'OC': ('OCI', 'Occitan', 'Occitan'),
    'OJ': ('OJI', 'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ'),
    'OR': ('ORI', 'Oriya', 'ଓଡ଼ିଆ'),
    'OM': ('ORM', 'Oromo', 'Afaan Oromoo'),
    'OS': ('OSS', 'Ossetian, Ossetic', 'Ирон Æвзаг'),
    'PI': ('PLI', 'Pali', 'पाऴि'),
    'PS': ('PUS', 'Pashto, Pushto', 'پښتو'),
    'FA': ('FAS', 'Persian', 'فارسی'),
    'PL': ('POL', 'Polish', 'Polski'),
    'PT': ('POR', 'Portuguese', 'Português'),
    'PA': ('PAN', 'Punjabi, Panjabi', 'ਪੰਜਾਬੀ, پنجابی‎'),
    'QU': ('QUE', 'Quechua', 'Runa Simi, Kichwa'),
    'RO': ('RON', 'Romanian, Moldavian, Moldovan', 'Română'),
    'RM': ('ROH', 'Romansh', 'Rumantsch Grischun'),
    'RN': ('RUN', 'Rundi', 'Ikirundi'),
    'RU': ('RUS', 'Russian', 'Русский'),
    'SE': ('SME', 'Northern Sami', 'Davvisámegiella'),
    'SM': ('SMO', 'Samoan', "Gagana Fa'a Samoa"),
    'SG': ('SAG', 'Sango', 'Yângâ Tî Sängö'),
    'SA': ('SAN', 'Sanskrit', 'संस्कृतम्'),
    'SC': ('SRD', 'Sardinian', 'Sardu'),
    'SR': ('SRP', 'Serbian', 'Српски Језик'),
    'SN': ('SNA', 'Shona', 'ChiShona'),
    'SD': ('SND', 'Sindhi', 'सिन्धी, سنڌي، سندھی‎'),
    'SI': ('SIN', 'Sinhala, Sinhalese', 'සිංහල'),
    'SK': ('SLK', 'Slovak', 'Slovenčina'),
    'SL': ('SLV', 'Slovenian', 'Slovenščina'),
    'SO': ('SOM', 'Somali', 'Soomaaliga, Af Soomaali'),
    'ST': ('SOT', 'Southern Sotho', 'Sesotho'),
    'ES': ('SPA', 'Spanish', 'Español'),
    'SU': ('SUN', 'Sundanese', 'Basa Sunda'),
    'SW': ('SWA', 'Swahili', 'Kiswahili'),
    'SS': ('SSW', 'Swati', 'SiSwati'),
    'SV': ('SWE', 'Swedish', 'Svenska'),
    'TL': ('TGL', 'Tagalog', 'Wikang Tagalog'),
    'TY': ('TAH', 'Tahitian', 'Reo Tahiti'),
    'TG': ('TGK', 'Tajik', 'Тоҷикӣ, Toğikī, تاجیکی‎'),
    'TA': ('TAM', 'Tamil', 'தமிழ்'),
    'TT': ('TAT', 'Tatar', 'Татарча, Tatarça, تاتارچا‎'),
    'TE': ('TEL', 'Telugu', 'తెలుగు'),
    'TH': ('THA', 'Thai', 'ไทย'),
    'BO': ('BOD', 'Tibetan', 'བོད་ཡིག'),
    'TI': ('TIR', 'Tigrinya', 'ትግርኛ'),
    'TO': ('TON', 'Tonga (Tonga Islands)', 'Faka Tonga'),
    'TS': ('TSO', 'Tsonga', 'Xitsonga'),
    'TN': ('TSN', 'Tswana', 'Setswana'),
    'TR': ('TUR', 'Turkish', 'Türkçe'),
    'TK': ('TUK', 'Turkmen', 'Türkmen, Түркмен'),
    'TW': ('TWI', 'Twi', 'Twi'),
    'UG': ('UIG', 'Uighur, Uyghur', 'Uyƣurqə, ئۇيغۇرچە‎'),
    'UK': ('UKR', 'Ukrainian', 'Українська'),
    'UR': ('URD', 'Urdu', 'اردو'),
    'UZ': ('UZB', 'Uzbek', 'Oʻzbek, Ўзбек, أۇزبېك‎'),
    'VE': ('VEN', 'Venda', 'Tshivenḓa'),
    'VI': ('VIE', 'Vietnamese', 'Tiếng Việt'),
    'VO': ('VOL', 'Volapük', 'Volapük'),
    'WA': ('WLN', 'Walloon', 'Walon'),
    'CY': ('CYM', 'Welsh', 'Cymraeg'),
    'WO': ('WOL', 'Wolof', 'Wollof'),
    'XH': ('XHO', 'Xhosa', 'IsiXhosa'),
    'YI': ('YID', 'Yiddish', 'ייִדיש'),
    'YO': ('YOR', 'Yoruba', 'Yorùbá'),
    'ZA': ('ZHA', 'Zhuang, Chuang', 'Saɯ Cueŋƅ, Saw Cuengh'),
    'ZU': ('ZUL', 'Zulu', 'IsiZulu'),
}

CURRENCIES_DICT = {
    'RUB': ('Russian Ruble', 'Российский рубль'),
    'USD': ('United States Dollar', 'American Dollar'),
    'EUR': ('Euro', 'Euro'),
    'BYN': ('Belarusian Ruble', 'Белорусский рубль'),
    'UAH': ('Ukrainian Hryvnia', 'Українська гривня'),
    'GBP': ('British Pound Sterling', 'Pound Sterling'),
    'CHF': ('Swiss Franc', 'Schweizer Franken'),
    'BRL': ('Brazilian Real', 'Real Brasileiro'),
    'SEK': ('Swedish Krona', 'Svensk krona'),
    'NOK': ('Norwegian Krone', 'Norsk krone'),
    'DKK': ('Danish Krone', 'Dansk krone'),
    'CZK': ('Czech Koruna', 'Česká koruna'),
    'PLN': ('Polish Zloty', 'Polski złoty'),
    'HUF': ('Hungarian Forint', 'Magyar forint'),
    'RON': ('Romanian Leu', 'Leu românesc'),
    'TRY': ('Turkish Lira', 'Türk Lirası'),
}

LEVEL_ORDERS_CODES = {
    LevelSystemNamesEnum.CEFR: {LevelOrderEnum.o_1: LevelCEFRCodesEnum.A1,
                                LevelOrderEnum.o_2: LevelCEFRCodesEnum.A2,
                                LevelOrderEnum.o_3: LevelCEFRCodesEnum.B1,
                                LevelOrderEnum.o_4: LevelCEFRCodesEnum.B2,
                                LevelOrderEnum.o_5: LevelCEFRCodesEnum.C1,
                                LevelOrderEnum.o_6: LevelCEFRCodesEnum.C2},
}

CELERY_TASK_PRIORITIES = {
    TasksNamesEnum.words_identify_level_task: QueueTaskPrioritiesEnum.q_1,
    TasksNamesEnum.texts_create_words_from_text: QueueTaskPrioritiesEnum.q_1,
    TasksNamesEnum.texts_identify_language_and_level_task: QueueTaskPrioritiesEnum.q_2,
    TasksNamesEnum.texts_identify_level_task: QueueTaskPrioritiesEnum.q_2,
    TasksNamesEnum.texts_identify_language_task: QueueTaskPrioritiesEnum.q_2,
}
PARTS_OF_SPEECH = {
    LanguagesISO2NamesEnum.RU: {
        "ADJ": "прилагательное",
        "ADP": "предлог",
        "ADV": "наречие",
        "AUX": "вспомогательный глагол",
        "CCONJ": "сочинительный союз",
        "DET": "определитель",
        "INTJ": "междометие",
        "NOUN": "существительное",
        "NUM": "числительное",
        "PART": "частица",
        "PRON": "местоимение",
        "PROPN": "имя собственное",
        "PUNCT": "пунктуация",
        "SCONJ": "подчинительный союз",
        "SYM": "символ",
        "VERB": "глагол",
        "X": "другие"
    },
    LanguagesISO2NamesEnum.EN: {
        "ADJ": "adjective",
        "ADP": "adposition",
        "ADV": "adverb",
        "AUX": "auxiliary verb",
        "CCONJ": "coordinating conjunction",
        "DET": "determiner",
        "INTJ": "interjection",
        "NOUN": "noun",
        "NUM": "numeral",
        "PART": "particle",
        "PRON": "pronoun",
        "PROPN": "proper noun",
        "PUNCT": "punctuation",
        "SCONJ": "subordinating conjunction",
        "SYM": "symbol",
        "VERB": "verb",
        "X": "other"
    },
    LanguagesISO2NamesEnum.DE: {
        "ADJ": "Adjektiv",
        "ADP": "Adposition",
        "ADV": "Adverb",
        "AUX": "Hilfsverb",
        "CCONJ": "nebenordnende Konjunktion",
        "DET": "Determiner",
        "INTJ": "Interjektion",
        "NOUN": "Substantiv",
        "NUM": "Numerale",
        "PART": "Partikel",
        "PRON": "Pronomen",
        "PROPN": "Eigenname",
        "PUNCT": "Interpunktion",
        "SCONJ": "unterordnende Konjunktion",
        "SYM": "Symbol",
        "VERB": "Verb",
        "X": "anderes"
    },
    LanguagesISO2NamesEnum.FR: {
        "ADJ": "adjectif",
        "ADP": "adposition",
        "ADV": "adverbe",
        "AUX": "verbe auxiliaire",
        "CCONJ": "conjonction de coordination",
        "DET": "déterminant",
        "INTJ": "interjection",
        "NOUN": "nom",
        "NUM": "numéral",
        "PART": "particule",
        "PRON": "pronom",
        "PROPN": "nom propre",
        "PUNCT": "ponctuation",
        "SCONJ": "conjonction de subordination",
        "SYM": "symbole",
        "VERB": "verbe",
        "X": "autre"
    },
    LanguagesISO2NamesEnum.IT: {
        "ADJ": "aggettivo",
        "ADP": "adposizione",
        "ADV": "avverbio",
        "AUX": "verbo ausiliare",
        "CCONJ": "congiunzione coordinante",
        "DET": "determinante",
        "INTJ": "interiezione",
        "NOUN": "sostantivo",
        "NUM": "numerale",
        "PART": "particella",
        "PRON": "pronome",
        "PROPN": "nome proprio",
        "PUNCT": "punteggiatura",
        "SCONJ": "congiunzione subordinante",
        "SYM": "simbolo",
        "VERB": "verbo",
        "X": "altro"
    },
    LanguagesISO2NamesEnum.ES: {
        "ADJ": "adjetivo",
        "ADP": "adposición",
        "ADV": "adverbio",
        "AUX": "verbo auxiliar",
        "CCONJ": "conjunción de coordinación",
        "DET": "determinante",
        "INTJ": "interjección",
        "NOUN": "sustantivo",
        "NUM": "numeral",
        "PART": "partícula",
        "PRON": "pronombre",
        "PROPN": "nombre propio",
        "PUNCT": "puntuación",
        "SCONJ": "conjunción de subordinación",
        "SYM": "símbolo",
        "VERB": "verbo",
        "X": "otro"
    },
    LanguagesISO2NamesEnum.PT: {
        "ADJ": "adjetivo",
        "ADP": "adposição",
        "ADV": "advérbio",
        "AUX": "verbo auxiliar",
        "CCONJ": "conjunção coordenativa",
        "DET": "determinante",
        "INTJ": "interjeição",
        "NOUN": "substantivo",
        "NUM": "numeral",
        "PART": "partícula",
        "PRON": "pronome",
        "PROPN": "nome próprio",
        "PUNCT": "pontuação",
        "SCONJ": "conjunção subordinativa",
        "SYM": "símbolo",
        "VERB": "verbo",
        "X": "outro"
    }
}
