"""1_create_tables

Revision ID: 5cd5c3cd574b
Revises: 182514e6040b
Create Date: 2024-05-13 16:40:25.188884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cd5c3cd574b'
down_revision = '182514e6040b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_index',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_storage_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_storage_uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('language',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=10), server_default=sa.text("'UTC+3'::character varying"), nullable=False),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.Column('is_accepting_emails', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_accepting_interface_messages', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_accepting_telegram', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('level',
    sa.Column('language_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('cefr_code', sa.String(length=2), nullable=False),
    sa.Column('native_code', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_uuid'], ['language.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_level_language_uuid'), 'level', ['language_uuid'], unique=False)
    op.create_table('grammar',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('language_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_uuid'], ['language.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_uuid'], ['level.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_grammar_language_uuid'), 'grammar', ['language_uuid'], unique=False)
    op.create_index(op.f('ix_grammar_level_uuid'), 'grammar', ['level_uuid'], unique=False)
    op.create_table('phrase',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['level_uuid'], ['level.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('readstash_text',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['level_uuid'], ['level.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('word',
    sa.Column('characters', sa.String(length=50), nullable=False),
    sa.Column('language_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_uuid'], ['language.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_uuid'], ['level.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_word_language_uuid'), 'word', ['language_uuid'], unique=False)
    op.create_index(op.f('ix_word_level_uuid'), 'word', ['level_uuid'], unique=False)
    op.create_table('word_file_user_status',
    sa.Column('word_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_index_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_index_uuid'], ['file_index.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_uuid'], ['word.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'word_uuid', 'file_index_uuid', 'status', name='unique_user_uuid_word_uuid_file_index_uuid')
    )
    op.create_index(op.f('ix_word_file_user_status_status'), 'word_file_user_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_file_user_status_status'), table_name='word_file_user_status')
    op.drop_table('word_file_user_status')
    op.drop_index(op.f('ix_word_level_uuid'), table_name='word')
    op.drop_index(op.f('ix_word_language_uuid'), table_name='word')
    op.drop_table('word')
    op.drop_table('readstash_text')
    op.drop_table('phrase')
    op.drop_index(op.f('ix_grammar_level_uuid'), table_name='grammar')
    op.drop_index(op.f('ix_grammar_language_uuid'), table_name='grammar')
    op.drop_table('grammar')
    op.drop_index(op.f('ix_level_language_uuid'), table_name='level')
    op.drop_table('level')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('language')
    op.drop_table('file_index')
    # ### end Alembic commands ###
