services:

  postgres_keycloak:
    ports:
      - "5433:5432"
    expose:
      - "5432"
    env_file:
      - ../../.envs/.docker-compose-local/.keycloak_readstash


  keycloak:
    env_file:
      - ../../.envs/.docker-compose-local/.keycloak_readstash
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./config/realm-export:/opt/keycloak/data/import
    command:
      - start-dev