services:

  postgres_keycloak:
    build:
      context: ../..
      dockerfile: ./docker/keycloak_readstash/DockerfilePostgres
    container_name: postgres_keycloak_readstash
    restart: always
    volumes:
      - postgres_keycloak_readstash_data_vol:/var/lib/postgresql/data
    networks:
      - shared_network
      - local_network

  keycloak:
    build:
      context: ../..
      dockerfile: ./docker/keycloak_readstash/Dockerfile
    container_name: keycloak
    restart: always
    networks:
      - shared_network
      - local_network

networks:
  shared_network:
    external: true
  local_network:
    driver: bridge
volumes:
  postgres_keycloak_readstash_data_vol: {}